### PR TITLE
Fix dependency on correct pybind11-abi package and add test to check that the correct abi version is used

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/conda-forge/pybind11-feedstock/issues/96
Fix part P1 of https://github.com/conda-forge/pybind11-feedstock/issues/95 (see https://github.com/conda-forge/pybind11-feedstock/issues/95#issuecomment-2366764770).

As now the abi version is no uniquely determined by the pybind11 version, the test on `pybind11-abi` package just check if the set abi is among the one defined in the header (see https://github.com/AnacondaRecipes/pybind11-feedstock/pull/15), while the actual tested is moved to the `pybind11` package, where it is indeed checked that the value of the macro `PYBIND11_INTERNALS_VERSION` actually defined matches the value used in the `run_export` .

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by henryiii** [comment]
This isn’t true anymore, the latest versions of the last three releases don’t require matching ABI versions anymore.

**Comment by henryiii** [comment]
Only the platform part needs to match, the internals ABI version does not matter. Though both extensions need to be compiled with the last release of 2.11, 2.12, or 2.13.

**Comment by traversaro** [comment]
Thanks for the input! Is this related to https://github.com/pybind/pybind11/pull/5296 ?

**Comment by henryiii** [comment]
Yes, that’s it. We probably should make branches and build 2.11.2 and 2.12.1. And I’m assuming we would like to try to get conda-forge packages to rebuild with the latest pybind11 releases.

**Comment by traversaro** [comment]
> And I’m assuming we would like to try to get conda-forge packages to rebuild with the latest pybind11 releases.

Probably we need anyhow to distinguish somehow packages built before and after https://github.com/pybind/pybind11/pull/5296 . Perhaps we could bump pybind11-abi to some arbitrary number (like 10) to signal that `pybind11-abi` stopped tracking `PYBIND11_INTERNALS_VERSION` and is not used instead to distinguish between before (pybind-abi<=4) and after (pybind-abi==10) https://github.com/pybind/pybind11/pull/5296 .

**Comment by traversaro** [comment]
Let's move the discussion back on the issues, for now this can be closed.

**Pull request closed without merging**
