### PR TITLE
Fix test for pybind11 include on conda

### PR DESCRIPTION
**Pull request by henryiii**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This fixes the tests to make sure that the pybind11 include exists, rather than just assuming the base folder is the correct one. I expect this to fail, since currently the conda package does report the correct include directory.

### CODE REVIEW

**Comment by henryiii** [comment]
@conda-forge-admin, please rerender

**Comment by henryiii** [comment]
The problem is that this installs to `${PREFIX}/include/python3.8/*` but reports `${PREFIX}/include` for the include directory.

**Comment by henryiii** [comment]
> Please do NOT check only for file existence, that will always be true

No, it was not true, this is why the PR failed until the patch was applied. The expected behavior is that `pybind11.get_include()` will return the include directory that contains the pybind11 folder with the pybind11 headers. It was not doing so. It was returning `$PREFIX/include`, which only contained `pythonX.X`.

It's a separate issue if that include directory is not the directory that is expected on conda that will also need fixing. I believe that this is being set by

https://github.com/conda-forge/pybind11-feedstock/blob/abbc6f7e8598c7b092c7189f981f8ca12a648acb/recipe/build.sh#L7

But only for unix (it's not in bld.bat), so I think on unix systems this is going into the nested folder. We can test this too, but we need to know whether it's supposed to be `$PREFIX/include` or `$PREFIX/include/pythonX.X` on conda.

**Comment by henryiii** [comment]
(I can test this out locally later and will update if we need to change the include location)

**Comment by ax3l** [comment]
Okay, I think the actual patch we need for CF is to avoid writing the nested folder in the first place.

**Comment by ax3l** [comment]
Got it, it's a unix-only problem, a leftover from #32. 
Patch proposed in #44, thanks again for spotting this! Dang, how could we forgot to check *as well* for file existence...

**Comment by ax3l** [comment]
Thank you again for your spotting and reporting this!
I applied the patch for Unix in #44 and will close this PR so it does not get accidentally merged.

**Comment by henryiii** [comment]
44 and this PR are identical, by the way. Only change is I forgot to delete the unused patch yet. It's okay, though.

**Comment by ax3l** [comment]
Cheese, I did not see that you also adjusted `build.sh` in the last diff. Sorry for that! The additional patch that you applied is still in this PR though and should not be in (`remconda.patch `).

Yes, this commit is the central one: https://github.com/conda-forge/pybind11-feedstock/pull/44/commits/f649a319e639eb5609a9e4379995ba11ba930520

**Pull request closed without merging**
