### PR TITLE
TST adding pybind11 osx exception test

### PR DESCRIPTION
**Pull request by beckermr**
We want to add this test of exception passing in pybind11 on osx here so that we can use it to test builds of libcxx. The backstory is that when we also built libcxxabi on osx, we saw issues where the RTTI was not making it between different compilations. We figured out that by having only one copy of the libcxxabi lib (i.e., just the system one and not the one on conda), it fixed this issue. Going forward, we want to run this pybind11-based test each time we build libcxx for osx.

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
cc @brianv0 This test is for a linking issue that was causing build failures for lsst/pex_exceptions. Good to know about in case we start seeing issues as the stack moves to conda-packaged clang.

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
related to https://github.com/conda-forge/libcxx-feedstock/pull/62

cc @isuruf

**Comment by beckermr** [comment]
> Thank you for the detailed work on this, LGTM although it is a bit involved.

Yes. The example code is a much-simplified version of the code in the repo lsst/pex_exceptions where I ran into this issue the first time.

**Comment by beckermr** [comment]
OK. I'm ready to merge when you all are!

**Comment by wjakob** [comment]
I don't fully understand why this commit was submitted to the feedstock rather than the main pybind11 repo.

**Comment by beckermr** [comment]
The bug and test for it is related to how conda-forge packages the libcxxabi, not pybind11 itself AFAICT. This is the main motivation.

**Comment by wjakob** [comment]
To me, most of what is in this feedstock repo are magic incantations that are periodically exchanged with new incantations by bots. There are almost no pybind11-specific things here, mainly just the SHA hash that we change whenever there is a new testcase.

For this reason, I’m very much against a *huge* patch that changes tons of feedstock-related code, and which patches up a low level ABI issue that seems really specific to your project. Can you please host this directly in your project?

**Pull request closed without merging**
