### PR TITLE
Rebuild python39 0 2 he4191d

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #54

### CODE REVIEW

**Comment by henryiii** [comment]
Why is there so much extra stuff in the diff, like changes to the travis file? Also, currently, pybind11 segfaults (rarely on Linux, more often on macOS) with python 3.9.0 (working on solving this soon, PR being made to CPython, hoping for 3.9.1).

Next version in a few days should be PyPy and Python 3.9.x friendly.

**Comment by chrisburr** [comment]
> Why is there so much extra stuff in the diff, like changes to the travis file?

That comes from `@conda-forge-admin, please rerender` or `conda smithy rerender`. Everything outside of `recipe/` (and `conda-forge.yml`) is automatically generated and is an implementation detail of how conda-forge works.

**Comment by henryiii** [comment]
No, I mean in the `gh2146.diff` file that you added that has changes to pybind11's Travis file, which doesn't affect conda-forge at all. It should go away in the near future anyway, but I noticed all the odd changes.

**Comment by chrisburr** [comment]
Ah apologies! It's just the contents of https://github.com/pybind/pybind11/pull/2146. It contains a little more than strictly necessary but I guess it was easier to grab with https://github.com/pybind/pybind11/pull/2146.patch when it was originally applied in https://github.com/conda-forge/pybind11-feedstock/pull/46/.

(I don't know any details about the patch itself, it was already in master when the Python 3.9 migration PR was created.)

**Comment by tdegeus** [comment]
I'm experiencing the segmentation fault on macOS as well : https://github.com/conda-forge/python-goosefem-feedstock/pull/7 . I'll guess I'll just have to wait for the new version and retry ?

**Comment by henryiii** [comment]
Assuming that's Python 3.9.0? That will be fixed in Python 3.9.1. The 2.6.0 version of pybind11 will probably also try to trade the segfault for a leak if you are using exactly 3.9.0, see https://github.com/pybind/pybind11/pull/2576.

**Pull request merged**
