### PR TITLE
Unix: Fix Broken Include (& Add Test)

### PR DESCRIPTION
**Pull request by ax3l**
Add a check that the path is not only where we want it but files also exist.

Added without logic change to current builds (Re: #43).
Thanks to @henryiii  for reporting this! :sparkles: 

cc @sdebionne you might want to take a look at this (Re: #32)

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
ping @wjakob: this conda-forge bugfix for Unix builds ready to be reviewed & merged.

**Comment by henryiii** [comment]
Master should be checked before the next release to make sure it's still working (after this is merged).

**Comment by ax3l** [comment]
Yes, this will automatically be checked when it goes through here.

**Comment by ax3l** [comment]
(Just ammended the meta-data of the last commit to put authorship on you, since I did not see you also changed that line in #43.)

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
Excellent, now that it's your code I can review and merge it myself, too :-p

**Pull request merged**
